# Generated by Django 6.0 on 2025-12-07 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='description',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='is_active',
        ),
    ]
